# Site settings
title: 易AI Blog
SEOTitle: 易AI的博客 | 易AI
header-img: img/home_bg.png
email: yangjunfeng.xjtu@gmail.com
description: "这里是 易AI 的个人博客"
keyword: "易AI Blog, 博客, 个人网站, 互联网, Web, JavaScript, Vue, 前端, 设计"
url: "https://blog.yiai.art" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
#RSS: false
#weibo_username: lingyun0406
#zhihu_username: lingyun0406
#github_username: lingyun0406
#twitter_username: lingyun0406
#facebook_username:  lingyun0406
#linkedin_username:  lingyun0406

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: false # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: false

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: "UA-49627206-1" # Format: UA-xxxxxx-xx
ga_domain: yiai.art

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "一名专注于AI方向的独立开发者。<br/><b>Wechat</b>: lingyun0406<br/><strong>QQ</strong>: 305914638"
sidebar-avatar: https://resource.lxiangke.vip/images/lingyun0406.jpg # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: false # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends: false
